MODEL_PATHS = {
    "uts": {
        "scaler": "models/uts/sc_uts.pkl",
        "model": "models/uts/dt_uts.pkl",
    },
    "conductivity": {
        "scaler": "models/conductivity/sc_conductivity.pkl",
        "model": "models/conductivity/dt_conductivity.pkl",
    },
    "elongation": {
        "scaler": "models/elongation/sc_elongation.pkl",
        "model": "models/elongation/dt_elongation.pkl",
    },
}

FEATURES = {
    "uts": [
        "EMUL_OIL_L_TEMP_PV_VAL0",
        "STAND_OIL_L_TEMP_PV_REAL_VAL0",
        "GEAR_OIL_L_TEMP_PV_REAL_VAL0",
        "EMUL_OIL_L_PR_VAL0",
        "ROD_DIA_MM_VAL0",
        "QUENCH_CW_FLOW_EXIT_VAL0",
        "CAST_WHEEL_RPM_VAL0",
        "BAR_TEMP_VAL0",
        "QUENCH_CW_FLOW_ENTRY_VAL0",
        "GEAR_OIL_L_PR_VAL0",
        "STANDS_OIL_L_PR_VAL0",
        "TUNDISH_TEMP_VAL0",
        "RM_MOTOR_COOL_WATER__VAL0",
        "ROLL_MILL_AMPS_VAL0",
        "RM_COOL_WATER_FLOW_VAL0",
        "EMULSION_LEVEL_ANALO_VAL0",
        "castNo",
        "furnace_temp",
        "Wt(MT)",
        "%SI",
        "%FE",
        "%TI",
        "%V",
        "%MN",
        "OTHIMP",
        "%AL",
        "Diameter",
        "Coil"
    ],
    "conductivity": [
        "EMUL_OIL_L_TEMP_PV_VAL0",
        "STAND_OIL_L_TEMP_PV_REAL_VAL0",
        "GEAR_OIL_L_TEMP_PV_REAL_VAL0",
        "EMUL_OIL_L_PR_VAL0",
        "ROD_DIA_MM_VAL0",
        "QUENCH_CW_FLOW_EXIT_VAL0",
        "CAST_WHEEL_RPM_VAL0",
        "BAR_TEMP_VAL0",
        "QUENCH_CW_FLOW_ENTRY_VAL0",
        "GEAR_OIL_L_PR_VAL0",
        "STANDS_OIL_L_PR_VAL0",
        "TUNDISH_TEMP_VAL0",
        "RM_MOTOR_COOL_WATER__VAL0",
        "ROLL_MILL_AMPS_VAL0",
        "RM_COOL_WATER_FLOW_VAL0",
        "EMULSION_LEVEL_ANALO_VAL0",
        "castNo",
        "furnace_temp",
        "Wt(MT)",
        "%SI",
        "%FE",
        "%TI",
        "%V",
        "%MN",
        "OTHIMP",
        "%AL",
        "Diameter",
        "Coil"
    ],
    "elongation": [
        "EMUL_OIL_L_TEMP_PV_VAL0",
        "STAND_OIL_L_TEMP_PV_REAL_VAL0",
        "GEAR_OIL_L_TEMP_PV_REAL_VAL0",
        "EMUL_OIL_L_PR_VAL0",
        "ROD_DIA_MM_VAL0",
        "QUENCH_CW_FLOW_EXIT_VAL0",
        "CAST_WHEEL_RPM_VAL0",
        "BAR_TEMP_VAL0",
        "QUENCH_CW_FLOW_ENTRY_VAL0",
        "GEAR_OIL_L_PR_VAL0",
        "STANDS_OIL_L_PR_VAL0",
        "TUNDISH_TEMP_VAL0",
        "RM_MOTOR_COOL_WATER__VAL0",
        "ROLL_MILL_AMPS_VAL0",
        "RM_COOL_WATER_FLOW_VAL0",
        "EMULSION_LEVEL_ANALO_VAL0",
        "castNo",
        "furnace_temp",
        "Wt(MT)",
        "%SI",
        "%FE",
        "%TI",
        "%V",
        "%MN",
        "OTHIMP",
        "%AL",
        "Diameter",
        "Coil"
    ]
}


